# Generated by Django 3.1.6 on 2021-03-26 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 12, 13, 10, 4016, tzinfo=utc)),
        ),
    ]
