# Generated by Django 3.1.7 on 2021-04-06 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_category',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='post',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 13, 47, 54, 979249, tzinfo=utc)),
        ),
    ]
