# Generated by Django 3.1.7 on 2021-03-28 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210326_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 19, 21, 28, 885266, tzinfo=utc)),
        ),
    ]
