# Generated by Django 3.1.6 on 2021-02-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210220_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
