# Generated by Django 3.1.6 on 2021-02-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210214_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_category',
            name='super_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post_category'),
        ),
    ]
