# Generated by Django 3.1.6 on 2021-02-15 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_category_super_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_category',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post_category'),
        ),
    ]
