# Generated by Django 3.1.6 on 2021-02-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210215_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_category',
            old_name='super_category',
            new_name='subcategory',
        ),
    ]
