# Generated by Django 3.1.6 on 2021-02-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210215_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='post_category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Post_category'),
        ),
    ]
