# Generated by Django 3.1.6 on 2021-02-15 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210215_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='post_category',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post_category'),
        ),
    ]
