# Generated by Django 3.1.6 on 2021-02-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210215_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_category',
            old_name='subcategory',
            new_name='super_category',
        ),
    ]
