# Generated by Django 3.1.6 on 2021-02-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210215_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_category',
            name='SubCategories',
        ),
        migrations.AddField(
            model_name='post_category',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubCategories', to='blog.post_category'),
        ),
    ]
