# Generated by Django 3.1.6 on 2021-03-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210310_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_category',
            old_name='sub_category',
            new_name='parent_category',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default/pdefault.png', null=True, upload_to='Post_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default/udefault.png', null=True, upload_to='user_images'),
        ),
    ]
