# Generated by Django 3.1.6 on 2021-03-13 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210311_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نپسندیدم',
                'verbose_name_plural': 'نپسندیدم ها',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پسندیدم',
                'verbose_name_plural': 'پسندیدم ها',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='state',
        ),
        migrations.DeleteModel(
            name='Post_state',
        ),
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.dislike'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.like'),
        ),
    ]
