# Generated by Django 3.1.6 on 2021-03-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210313_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislike',
        ),
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(to='blog.Dislike'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(to='blog.Like'),
        ),
    ]
