# Generated by Django 3.1.6 on 2021-03-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210313_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='last_update',
        ),
    ]
